### ISSUE TITLE
[Installation] Checkpoint URL

### ISSUE THREAD

**Issue by longkhanh-fam** [KAIST-AILab/SyncVSR#1]
Great work !! Can you guy share the checkpoint URL

**Comment by snoop2head** [comment]
@longkhanh-fam 
Thank you for the compliment. We are currently preparing both the checkpoint for word-level and sentence-level VSR pretrained models. Code for sentence-level VSR will be released soon, so please stay tuned for updates!

**Comment by hanif-rt** [comment]
Awesome work! Am wondering if the checkpoint was shared? Release url is empty right now.

**Comment by snoop2head** [comment]
@hanif-rt 
Due to the rebuttals on recent conferences, code refactoring and weight sharing is taking a while...
Please hang on a bit! Will notify you as soon as we get ready!

**Comment by MonolithFoundation** [comment]
@snoop2head Does the model will be released? Also, does the model supports Chinese that mouth not very suitable angle to camera?

**Comment by snoop2head** [comment]
@MonolithFoundation 
Apologies for the delay! The word-level and sentence-level English model weights will be released soon, but the Chinese model won't be included. While preparing the paper, we discovered that the available Chinese word-level VSR dataset had issues with video and audio drifting out of sync, raising concerns about its reliability on out-of-domain dataset, despite its solid benchmark performance. I haven't had a chance to explore the new CN-CVS and CNVSRC dataset series yet—do you know if those datasets ensure proper video and audio synchronization?

**Comment by hanif-rt** [comment]
@snoop2head have you tried other audio codecs, apart from vq-wav2vec2?

And have you encountered issues with misaligned video and audio?

**Comment by MonolithFoundation** [comment]
If am not seeing wrong, does this work still need audio?

I have videos that not have audio at all, how to get words from it? Simple lip reading.

Why visual to words need audio? if there is audio, the ASR it decent nowadays.

**Comment by snoop2head** [comment]
@hanif-rt @MonolithFoundation 
**Before I start, it would be appreciated if separate issues could be filed. This will make it easier for others to follow along.**

---

@hanif-rt 
We have experimented with both vq-wav2vec and wav2vec 2.0, utilizing the early quantization segment from wav2vec 2.0. You can refer to the code below for details:

https://github.com/KAIST-AILab/SyncVSR/blob/4f51376eb023d44c67818c063235c30192d212d1/LRW/video/src/lightning.py#L65-L78

Our work shares some limitations with other semi-supervised VSR approaches like Raven and AV-HuBERT, as it requires aligned video and audio for training. However, as long as there isn’t significant misalignment, it is robust enough, as demonstrated in the CAS-VSR-W1K benchmark.

---

@MonolithFoundation 

Yes, audio is required during training, **but not during the inference.** I will release the checkpoints as soon as I submit to the upcoming conference. Apologies for the delay—I've got over 100 checkpoints from different ablation studies to sort through.

---

Thank you for your patience once again, and we'll get back to you shortly.

**Comment by MonolithFoundation** [comment]
@snoop2head  thannks for the reply, have u test on wild Chinese videos? Does it could works well?

**Comment by snoop2head** [comment]
@MonolithFoundation 

Please create a separate issue 😅

We've only evaluated our work on CAS-VSR-W1K (previously LRW-1000), which is considered an "in the wild" setup. However, since this is limited to word-level VSR, there's definitely room for further exploration. Do you have any suggestions for sentence-level VSR datasets?

For the Chinese neural audio quantizer, we used wav2vec 2.0 from [kehanlu/mandarin-wav2vec2](https://github.com/kehanlu/Mandarin-Wav2Vec2). If a sentence-level VSR dataset, similar to LRS2 or LRS3, is available, adapting the SyncVSR framework should be quite straightforward.

**Comment by MonolithFoundation** [comment]
Apologies for directly applying to an unrelated issue. Let us discuss in a separate place. I believe that wild and multilingual topics are worthy of in-depth discussion.

**Comment by snoop2head** [comment]
@longkhanh-fam @hanif-rt @MonolithFoundation 

Thank you for waiting. I've updated the model checkpoint and audio tokens that we used to get our results.
Please refer to the [release section](https://github.com/KAIST-AILab/SyncVSR/releases/tag/weight-audio-v1) of the repository!

**Comment by snoop2head** [comment]
If you have any inquiries, please reopen the issue or submit a new issue!
