### ISSUE TITLE
[Installation] Issues related to installation and preprocessing of the Chinese dataset.

### ISSUE THREAD

**Issue by daiyingjie2024** [KAIST-AILab/SyncVSR#12]
Sorry, please forgive my previous mistakes.I'm having some issues while trying to run your code. Is the version of Fairseq the latest one? Is it v0.12.2?

In addition, I have another question.I'm currently reviewing the code from the paper "Learn an Effective Lip Reading Model without Pains," and I just came across the prepare_lrw1000.py file that you mentioned earlier, but I’m not sure what processing was done to the dataset before running prepare_lrw1000.py. The author didn’t provide the code for directly processing the original dataset, which is quite confusing for me (as a beginner, I find it difficult to handle these tasks). If it wouldn’t trouble you too much, I would like to ask if you could share the relevant code;If this causes any inconvenience, I sincerely apologize. I shouldn’t have disturbed you. Please forgive me.

**Comment by snoop2head** [comment]
You don't have to apologize 🤗 

### LRW-1000 Preprocessing
CAS-VSR-W1K (LRW-1000) doesn't require additional RoI (Region of Interest) extraction for lip regions. Please adhere to the [instruction of dataset preparation](https://github.com/VIPL-Audio-Visual-Speech-Understanding/learn-an-effective-lip-reading-model-without-pains/tree/master?tab=readme-ov-file#dataset-preparation). It doesn't take long, just downloading and running the script. 

### Fairseq Version
We recommend using the latest one, but fairseq has several issues in installation and using vq-wav2vec. I will update installation method which make fairseq usage optional. Before then, please use tokenized audios in [audio_tokens.tar](https://github.com/KAIST-AILab/SyncVSR/releases/tag/weight-audio-v1) in release section or use wav2vec 2.0.

**Comment by daiyingjie2024** [comment]
> ### LRW-1000 Preprocessing
> CAS-VSR-W1K (LRW-1000) doesn't require additional RoI (Region of Interest) extraction for lip regions. Please adhere to the [instruction of dataset preparation](https://github.com/VIPL-Audio-Visual-Speech-Understanding/learn-an-effective-lip-reading-model-without-pains/tree/master?tab=readme-ov-file#dataset-preparation). It doesn't take long, just downloading and running the script.

Thank you for your patient answers. Regarding the point you mentioned, the audio portion of the CAS-VSR-W1K (LRW-1000) I downloaded is in wav format (I'm not sure if I downloaded it incorrectly). There is no code for extracting it into npy files, and the prepare_lrw1000.py script requires npy files, which confuses me. I'm not sure what should be saved in this npy file. Is it a one-dimensional array representing the sampled values of the audio signal? Are there any specific requirements for converting from wav to npy?

**Comment by snoop2head** [comment]
It might be helpful to reach out to the authors of the LRW-1000 dataset or check the discussion on this [LRW-1000 repository's issue](https://github.com/VIPL-Audio-Visual-Speech-Understanding/learn-an-effective-lip-reading-model-without-pains/issues/7). I personally think that there's not much ambiguity in converting wav to npy format though.

For your reference, we used the function in our code [SyncVSR/LRS/video/preprocess/utils.py](https://github.com/KAIST-AILab/SyncVSR/blob/main/LRS/video/preprocess/utils.py#L13-L21)

https://github.com/KAIST-AILab/SyncVSR/blob/09e91a05faef834fe4432de6d469f987540ed9c0/LRS/video/preprocess/utils.py#L13-L21

If you run it on LRW1000, it will yield the result of following:

```python3
sample_idx = 0
audio_path = "./LRW1000_Public/audio"
audio_files = glob(os.path.join(audio_path, "*.wav"))
audio = AudioSegment.from_file(audio_files[sample_idx], format="wav")
audio_np, sample_rate = pydub_to_np(audio)
audio_np = audio_np.squeeze()
print(audio_np)
```

```
array([-0.00765991, -0.00863647, -0.01223755, ..., -0.05758667, -0.06567383, -0.07342529], dtype=float32)
```

**Comment by snoop2head** [comment]
@daiyingjie2024 

Installation method has been updated! Please refer to [the Installation guide on README](https://github.com/KAIST-AILab/SyncVSR?tab=readme-ov-file#installation).
