### ISSUE TITLE
[Training] Request for Accuracy Graphs to Address Replication Issues

### ISSUE THREAD

**Issue by davidingram123** [KAIST-AILab/SyncVSR#14]
Hi, I read your paper and found it very interesting. However, I encountered some issues with the code, and I am unable to replicate your results. Could you share the "train/accuracy_top1" and "val/accuracy_top1" graphs over 200 epochs (or more) with me? This would give me a reference, as I noticed that when running the code, the "val/accuracy_top1" graph tends to plateau between 40 and 50 epochs.(It might be that I missed a data augmentation strategy, but it shouldn't cause such a significant drop in accuracy, right?)
![W B Chart 2024_10_19 13_11_17](https://github.com/user-attachments/assets/7792157b-1639-4af3-9b15-6db41ed24420)
![W B Chart 2024_10_19 13_13_34](https://github.com/user-attachments/assets/49b6ddb6-2563-4895-a6a3-0737112e2f26)

**Comment by davidingram123** [comment]
The configuration file I used is bert-12l-512d_LRW_96_bf16_rrc_WB, with some minor modifications, no more than two.

**Comment by snoop2head** [comment]
@davidingram123 

**Data augmentation strategy is crucial as stated by [Ma et al 2022](https://arxiv.org/pdf/2209.01383), so please, stick with our implementations for replication purpose.**

## [🔗 WandB Report](https://wandb.ai/quoqa-nlp/cross-modal-sync/reports/LRW-Training-Log--Vmlldzo5Nzc5MDQ4?accessToken=b1o90x4tiiq1tvttq7hl1re31ts05njoq18sfmb6haak784en6lpu05zzc46you4)

<img width="732" alt="Screenshot 2024-10-19 at 2 31 41 PM" src="https://github.com/user-attachments/assets/ce9e1e28-b7cf-4087-9d6c-931a4aade7d3">

<img width="732" alt="Screenshot 2024-10-19 at 2 31 55 PM" src="https://github.com/user-attachments/assets/21af2cc0-2424-4436-8ed4-ab02735c37da">

**val/accuracy_top1 plateau around 95.1% ~ 95.2% and train/accuracy_top1 oscillates around 80%.** For more details, please refer to our attached wandb training log of word-level VSR above.

**Comment by davidingram123** [comment]
Thank you for your help.

**Comment by snoop2head** [comment]
Your welcome! Please file another issue if you need any further help! @davidingram123
