### ISSUE TITLE
[Preprocessing] Questions related to preprocessing

### ISSUE THREAD

**Issue by davidingram123** [KAIST-AILab/SyncVSR#16]
list_landmarks = np.zeros((478, 3)).tolist()
Is this line of code wrong? Shouldn't it be 468?
I don't know where the issue is; I just have a feeling that the generated .pkl files are not correct, or that the data preprocessing is not right. Could you also show me the  details corresponding to the LRW_CKPT_epoch_167_step_213864.ckpt you provided?

Sequential(
  (0): FunctionalModule()
  (1): RandomHorizontalFlip(p=0.5)
  (2): RandomResizedCrop(size=(96, 96), scale=(0.6, 1.0), ratio=(0.75, 1.3333), interpolation=bilinear, antialias=warn)
  (3): Grayscale(num_output_channels=1)
  (4): TimeMask()
  (5): Normalize(mean=0.421, std=0.165)
)
Should the following line of code be executed before the above content?Or should it not be executed?
video = 2 * video.float() / 0xFF - 1

**Comment by snoop2head** [comment]
Hi @davidingram123 

1. The value of 478 is actually correct. Here's an example to illustrate how the face coordinate numpy file should look:

```
>>> import numpy as np
>>> print(np.load("ABOUT_00001.npy").shape)
(29, 478, 3)
```
2. This might be related to the issue you mentioned in #15. I would recommend starting by visualizing the video contents of your .pkl files to ensure they are processed correctly.
3. If you're asking for more details, could you please clarify what specific information you're looking for?  You can refer to the Dataset Preprocessing section in our [SyncVSR paper](https://arxiv.org/pdf/2406.12233) for more background. Additionally, the preprocessing script is available in the repository at [LRW/video/src/preprocess_pkl.py](https://github.com/KAIST-AILab/SyncVSR/blob/main/LRW/video/src/preprocess_pkl.py) and [LRW/video/src/preprocess_roi.py](https://github.com/KAIST-AILab/SyncVSR/blob/main/LRW/video/src/preprocess_roi.py). 
4. Regarding the line of code you're asking about, it’s actually commented out in the [source file](https://github.com/KAIST-AILab/SyncVSR/blob/8a3fadc455c68e85ac54bf8bc1b55d60a33d407f/LRW/video/src/data.py#L40), , meaning it won't be executed. If you still have concerns, please cite the specific line of code using GitHub’s "Reference in New Issue" or "Copy Permalink" functions, and I'll be happy to assist further.

I’m happy to help with any project-related questions, but it would be great if you could provide specific details, such as the visualization results of the data or the exact code you’re referring to. That will allow me to better understand and address your concerns.

**Comment by davidingram123** [comment]
![npy 2024-10-19 171456](https://github.com/user-attachments/assets/18574d19-e5d1-4519-9b68-d72f4f09ade9)
thank you, this is the visualization of the npy file and the corresponding content in the pkl file.

**Comment by snoop2head** [comment]
@davidingram123 
Thank you for sharing the visualization! With no need to post all 29 frames in the issue section, just for your personal reference, I recommend comparing the original video and the face landmark video side-by-side for all 29 frames, as demonstrated below: 

|          Original Video          |                  Face Landmark Video                   |
| :------------------------------: | :----------------------------------------------------: |
![BRITAIN](https://github.com/user-attachments/assets/d87a3915-1d06-4507-bd7c-0f65de4c7db8) |  ![BRITAIN_coordinate](https://github.com/user-attachments/assets/b2e3fa60-7143-4266-9d06-63b06f509f1c) |

Now, back to debugging! From my perspective, it looks like the coordinates have been extracted correctly. 
 I suspect the cropping step based on these coordinates, in the [LRW/video/src/preprocess_pkl.py](https://github.com/KAIST-AILab/SyncVSR/blob/main/LRW/video/src/preprocess_pkl.py) script, could be causing the issue with the output.

To investigate further, you might want to print() and breakpoint() the coordinates at this part of the code:

https://github.com/KAIST-AILab/SyncVSR/blob/8a3fadc455c68e85ac54bf8bc1b55d60a33d407f/LRW/video/src/preprocess_pkl.py#L108-L130

and check which region is being cropped in the video. 

I will check the [LRW/video/src/preprocess_pkl.py](https://github.com/KAIST-AILab/SyncVSR/blob/main/LRW/video/src/preprocess_pkl.py) process in the meantime.

**Comment by davidingram123** [comment]
![dafa](https://github.com/user-attachments/assets/76a61be9-5c4d-4483-902c-12a2b37984c1)

Hello, the value printed out is like this. Is it correct?

**Comment by davidingram123** [comment]
When I replaced all instances of the number 160 with 256 in the [preprocess_pkl.py](https://github.com/KAIST-AILab/SyncVSR/blob/main/LRW/video/src/preprocess_pkl.py) file, I got the above results. Is this approach correct?

**Comment by snoop2head** [comment]
@davidingram123 Yes that's correct!
I think I confused with LRS's resolution (160 x 160) with LRW's (256 x 256) when I was refactoring my code before the public release. I will fix it accordingly.
Thank you for your feedback!
