### ISSUE TITLE
Question about output modality

### ISSUE THREAD

**Issue by Liajun** [KAIST-AILab/SyncVSR#21]
Hello, I apologize for asking, but does this source code ultimately output text or speech? What is the downstream task? I understand that the major innovation of this paper is aligning the visual encoder with the audio, similar to contrastive learning. Therefore, I am unclear whether the final output is text or speech. I'm sorry to bother you.

**Comment by snoop2head** [comment]
Hello @Liajun ,

Q1. Does this source code ultimately output text or speech?

As stated in [our paper](https://arxiv.org/pdf/2406.12233), our primary objective is speech recognition, with the ultimate goal being to decode an accurate text transcription of spoken words. In the inference stage, the speech token generation component is omitted, as illustrated in the diagram below:

<img width="450" alt="image" src="https://github.com/KAIST-AILab/SyncVSR/blob/main/assets/Sentence_Level_VSR.png?raw=true">

Q2. What is the downstream task?

There isn’t a downstream task in our case, as our framework is end-to-end, focusing on visual speech recognition. For instance, our pretrained Vox+LRS2+LRS3 model was directly applied to both the LRS2 and LRS3 datasets without fine-tuning.

Q3. I understand that the major innovation of this paper is aligning the visual encoder with the audio, similar to contrastive learning

Thank you for recognizing our work’s innovation! However, it’s important to clarify that our approach differs from contrastive learning. While contrastive learning is matching negative vs positive pairs within the batch, our method generates audio tokens at a frame-level. If we were to identify a comparable self-supervised task, it would be [ELECTRA](https://arxiv.org/pdf/2003.10555), as discussed in our introduction. The key aspect of our methodology lies in fine-grained, frame-level cross-modal generation. Contrastive learning, on the other hand, rather captures global information.

Q4.  I am unclear whether the final output is text or speech
Please refer back to Q1 and the accompanying diagram: while the outputs include both speech tokens and text tokens, our end-goal is precise text transcription.

**Comment by Liajun** [comment]
Thank you very much for your patient explanation.

**Comment by snoop2head** [comment]
@Liajun 
Good to know! I will close the issue for now. Please file a new one or reopen the issue if you have any questions.
