### ISSUE TITLE
[Training] Training log of sentence-level VSR

### ISSUE THREAD

**Issue by davidingram123** [KAIST-AILab/SyncVSR#24]
@snoop2head  Hello, could you please share the training log of sentence-level VSR?

**Comment by snoop2head** [comment]
Here's the [🔗 link](https://api.wandb.ai/links/quoqa-nlp/t4ey9rkl)!
I may reply late due to ongoing rebuttal process, but please feel free to leave any questions or requests on the issue section.

**Comment by davidingram123** [comment]
Sorry to bother you, and thank you so much for your help. I've found the cause of my mistake.
