### ISSUE TITLE
[Training] `vq-wav2vec_kmeans.pt` and `fairseq`

### ISSUE THREAD

**Issue by Tomas542** [KAIST-AILab/SyncVSR#25]
Can you add `./vq-wav2vec_kmeans.pt` weights to the release like you did with the other weights? Or is it the same as just `Wav2Vec2`?

Also, could you please provide the version of `fairseq` you used? Or tell me where you provided it if you have already done so please)

**Comment by snoop2head** [comment]
Hello @Tomas542 !
Thank you for your interest in our work.

`vq-wav2vec_kmeans.pt` is fully available at [fairseq repository](https://github.com/facebookresearch/fairseq/blob/main/examples/wav2vec/README.md#vq-wav2vec). You can download with the command below:

```shell
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/vq-wav2vec_kmeans.pt -P ./
```

Lastly, we used the fairseq version 0.12.2

**Comment by Tomas542** [comment]
Thanks a lot!
