### ISSUE TITLE
[Multilingual] can you test on  [CMLR](https://www.vipazoo.cn/CMLR.html)

### ISSUE THREAD

**Issue by wuhongsheng** [KAIST-AILab/SyncVSR#5]

**Comment by snoop2head** [comment]
Currently, I do not have computational resource available :(

For the Chinese neural audio quantizer, we used wav2vec 2.0 from [kehanlu/mandarin-wav2vec2](https://github.com/kehanlu/Mandarin-Wav2Vec2). If a sentence-level VSR dataset, similar to LRS2 or LRS3, is available, adapting the SyncVSR framework should be quite straightforward.
