### ISSUE TITLE
[Training] Train on custom dataset

### ISSUE THREAD

**Issue by Thaonguyennnee** [KAIST-AILab/SyncVSR#6]
I want to train the model on my custom Vietnamese sentence level dataset. Can anyone guide me? I wonder where the ./src/inference.py and ./src/train.py files are.

**Comment by wuhongsheng** [comment]
LRW/video/src

**Comment by snoop2head** [comment]
Sentence level VSR code is located at [LRS/video](https://github.com/KAIST-AILab/SyncVSR/tree/main/LRS/video). I will add repository architecture to the README, taking your advice!

**Comment by snoop2head** [comment]
I've updated the repositroy structure on [README](https://github.com/KAIST-AILab/SyncVSR?tab=readme-ov-file#repository-structure). Please refer to the README and if you have any questions, please file another issue or reopen the issue!

**Comment by Thaonguyennnee** [comment]
Can you provide me the pretrained of lrs. thanks in advance.
