### ISSUE TITLE
[Multilingual] Can you provide the training code for CAS-VSR-W1k?

### ISSUE THREAD

**Issue by wuhongsheng** [KAIST-AILab/SyncVSR#8]

**Comment by snoop2head** [comment]
We've used same training code on [LRW/video](https://github.com/KAIST-AILab/SyncVSR/tree/main/LRW/video) but with different preprocessing schemes. I will upload the preprocessing script ASAP.

**Comment by snoop2head** [comment]
It seems like we used the file from [prepare_lrw1000.py](https://github.com/VIPL-Audio-Visual-Speech-Understanding/learn-an-effective-lip-reading-model-without-pains/blob/master/scripts/prepare_lrw1000.py). Please refer to the attached file.
