### ISSUE TITLE
[Installation] Can you provide me the pretrained of lrs. thanks in advance.

### ISSUE THREAD

**Issue by Thaonguyennnee** [KAIST-AILab/SyncVSR#9]
Can you provide me the pretrained of lrs. thanks in advance.

_Originally posted by @Thaonguyennnee in https://github.com/KAIST-AILab/SyncVSR/issues/6#issuecomment-2404110753_

**Comment by snoop2head** [comment]
Uploaded! Please check the [release section](https://github.com/KAIST-AILab/SyncVSR/releases/tag/weight-audio-v1) for the detail.
